# Import Pandas

To use the Pandas library, you need to import it into your coding environment. For these exercises, our coding environment is this Jupyter notebook. Pandas is typically imported and named as "pd".

In [5]:
# import the pandas library and use the alias 'pd'
import pandas as pd

# Series

A series is a data type used by Pandas. It is like a one dimensional list, whose elements can be of any data type themselves.
Pandas contains a method, ``.Series()``, that initiates a series object from a Python list, tuple,

In [6]:
#create the s1 series from the list: [10,20,30,40,50]
s1 = pd.Series([10,20,30,40,50] ) 
print("The series values are:", s1.values)
print("The index values are:", s1.index.values)
# additional practice
# create a series called s_tuple from the tuple: ("apple", "banana", "cherry")

# create a series called s_dictionary from the dictionary: {"brand": "Ford", "model": "Mustang", "year": 1964}

The series values are: [10 20 30 40 50]
The index values are: [0 1 2 3 4]

In [3]:
# fill in the blank with the series values and index values
print("The s1 series values are:", #s1 values#)
print("The s1 index values are:", #s1 index values#)
      
      
      print("\n")
print("The s_tuple series values are:", #s_tuple values#)
print("The s_tuple index values are:", #s_tuple index values#)
print("\n")
print("The s_dictionary series values are:", #s_dictionary values#)
print("The s_dictionary index values are:", #s_dictionary index values#)

SyntaxError: unexpected EOF while parsing (<ipython-input-3-4a4e1ec92da3>, line 3)

Index values in a series are generated by default. We can also define custom indexes at the time of creating series.

Below is a series of marks (grades) and the associated subjects can be defined as custom row indexes.

In [7]:
# create the s2 series from the list [80,93,78,85,97] and with labeled indexes ['English','Science','Social','Tamil','Maths']

s2 = pd.Series([80,93,78,85,97], index=['English','Science','Social','Tamil','Maths'])
print("The Marks obtained by student are", s2)

The Marks obtained by student are English    80
Science    93
Social     78
Tamil      85
Maths      97
dtype: int64

In [ ]:
# print the s2 series

We can provide a name for the whole series, as well as a name for the indexes.

In [12]:
# assign the s2 series name to be "Student Marks"

s2 = StudentMarks

# assign the s2 index name to be "Subject"
#not sure?

NameError: name 'StudentMarks' is not defined

In [19]:
# print the s2 series again to see the newly assigned name and index name

print(StudentMarks)

AttributeError: 'str' object has no attribute 'values'

## Subsetting the Series

Values inside the series can be accessed using the ``[ ]`` square bracket slicing operation

- Series can be sliced using the default index
- Series can also be sliced using string indices (indexes)

In [14]:
# return the first element in the s2 series
s2[0]
#I know it's wrong.

'tud'

In [ ]:
# slicing using default integer index
# return the elements starting at position one and ending with the element at index 3

In [ ]:
# Slicing using string index
# return the element associated with the index 'Tamil'

## Creating a Series from a Dictionary

- A Python dictionary is a data structure which maps keys to a set of values.
- A dictionary contains key-value pairs.
- A series is similar to a dictionary in a way that it maps given indexes to a set of values.

Let's see how to create a series from a dictionary

I have a dictionary that represents fruits and prices. Let's create a series from this dictionary

In [15]:
# create a dictionary of fruit names and their prices. Use the values from the article
dict_fruits = { 'Orange':80,
          'Apples':210,
          'Bananas':50,
         'Grapes':90,
         'Watermelon':70}

In [16]:
# Lets convert this dictionary into a series
# use the pandas method .Series() 

fruits = pd.Series(dict_fruits)

In [22]:
# print the series
print("Fruits and pricesn", fruits)

print(fruits)

Fruits and pricesn Orange         80
Apples        210
Bananas        50
Grapes         90
Watermelon     70
dtype: int64
Orange         80
Apples        210
Bananas        50
Grapes         90
Watermelon     70
dtype: int64

In [20]:
# Slice the series and retrieve price of grapes
print(fruits['Grapes'])

90

# DataFrame

## Create a DataFrame from a Series object

Let's create a DataFrame from the marks series we created in the above step.

In [26]:
# create a dataframe from the s2 series
df_marks = pd.DataFrame(s2, columns=['Student1'])
#not sure what is wrong

ValueError: DataFrame constructor not properly called!

In [ ]:
# print the dataframe
print("The dataframe created from series isn",df_marks)

## Create a DataFrame from a Dictionary

Let's say we have 2 series of heights and weights of the same set of persons and we want to put it together in a table.

Here we can create dictionary using both series and create a DataFrame using the Pandas ``.DataFrame()`` method.

In [28]:
# Create height series using [5.3, 6.2,5.8,5.0,5.5] for values, ['Person 1','Person 2','Person 3','Person 4','Person 5'] for indexes
height = pd.Series([5.3, 6.2,5.8,5.0,5.5], index=['Person 1','Person 2','Person 3','Person 4','Person 5'])

# Create weight series (in kgs) using [65,89,75,60,59] for values and the same indexes as height
weight = pd.Series([65,89,75,60,59], index=['Person 1','Person 2','Person 3','Person 4','Person 5'])

In [29]:
# Create a dataframe from the height and weight series above
df_person = pd.DataFrame({'height': height, 'weight': weight})
# print the dataframe

print("The Person table details are:n", df_person)

The Person table details are:n           height  weight
Person 1     5.3      65
Person 2     6.2      89
Person 3     5.8      75
Person 4     5.0      60
Person 5     5.5      59